---
AWSTemplateFormatVersion: "2010-09-09"

Description: multiple sizes of nodes

Metadata:
  Instances:
    Description: "two compute nodes"
  Databases: 
    Description: "No databases involved here"

Parameters:

  KeyPair:
    Type: 'AWS::EC2::KeyPair::KeyName'
    Default: ivan-keypair
    Description: Name of an existing key pair to use for the instances

  InstanceAmi:
    Type: String
    Default: ami-04b88ad7b25bc74ef
    Description: An ami uploaded to AWS

  InstanceSize:
    Type: String
    Default: t3.small
    Description: Enter an instance size

  InstanceSize2:
    Type: String
    Default: c5.large
    Description: Enter an instance size

  InstanceSize3:
    Type: String
    Default: c5d.metal
    Description: Enter an instance size

  SecurityGroup:
    Type: String
    Default: sg-099219b43ee588b21
    Description: The security group that has already been set up.

  InstanceSubnet:
    Type: String
    Description: The subnet to be used.
    Default: subnet-55d8582f

  IpData:
    Type: String
    Description: ip data from the standalone node

  KeyData:
    Type: String
    Description: key data from the standalone node

Resources:


  Cnode01:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: 
        Ref: InstanceAmi
      InstanceType: 
        Ref: InstanceSize
      KeyName: 
        Ref: KeyPair 
      SecurityGroupIds: 
        - sg-099219b43ee588b21
      SubnetId: subnet-55d8582f
      UserData: !Base64 
          Fn::Join:
            - ''
            - - "#cloud-config\n"
              - "write_files:\n"
              - "  - content: |\n"
              - "      SERVER="
              - Ref: IpData
              - "\n"
              - "    path: /opt/flight/cloudinit.in\n"
              - "    permissions: '0644'\n"
              - "    owner: root:root\n"
              - "users:\n"
              - "  - default\n"
              - "  - name: root\n"
              - "    ssh_authorized_keys:\n"
              - "      - "
              - Ref: KeyData
              - "\n"

  Cnode02:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: 
        Ref: InstanceAmi
      InstanceType: 
        Ref: InstanceSize2
      KeyName: 
        Ref: KeyPair 
      SecurityGroupIds: 
        - sg-099219b43ee588b21
      SubnetId: subnet-55d8582f
      UserData: !Base64 
          Fn::Join:
            - ''
            - - "#cloud-config\n"
              - "write_files:\n"
              - "  - content: |\n"
              - "      SERVER="
              - Ref: IpData
              - "\n"
              - "    path: /opt/flight/cloudinit.in\n"
              - "    permissions: '0644'\n"
              - "    owner: root:root\n"
              - "users:\n"
              - "  - default\n"
              - "  - name: root\n"
              - "    ssh_authorized_keys:\n"
              - "      - "
              - Ref: KeyData
              - "\n"

  Cnode03:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: 
        Ref: InstanceAmi
      InstanceType: 
        Ref: InstanceSize3
      KeyName: 
        Ref: KeyPair 
      SecurityGroupIds: 
        - sg-099219b43ee588b21
      SubnetId: subnet-55d8582f
      UserData: !Base64 
          Fn::Join:
            - ''
            - - "#cloud-config\n"
              - "write_files:\n"
              - "  - content: |\n"
              - "      SERVER="
              - Ref: IpData
              - "\n"
              - "    path: /opt/flight/cloudinit.in\n"
              - "    permissions: '0644'\n"
              - "    owner: root:root\n"
              - "users:\n"
              - "  - default\n"
              - "  - name: root\n"
              - "    ssh_authorized_keys:\n"
              - "      - "
              - Ref: KeyData
              - "\n"