---
AWSTemplateFormatVersion: "2010-09-09"

Description: two compute nodes

Metadata:
  Instances:
    Description: "two compute nodes"
  Databases: 
    Description: "No databases involved here"

Parameters:

  KeyPair:
    Type: 'AWS::EC2::KeyPair::KeyName'
    Default: ivan-keypair
    Description: Name of an existing key pair to use for the instances

  InstanceAmi:
    Type: String
    Default: ami-04b88ad7b25bc74ef
    Description: An ami uploaded to AWS

  InstanceSize:
    Type: String
    Default: t3.small
    Description: Enter an instance size

  SecurityGroup:
    Type: String
    Default: sg-099219b43ee588b21
    Description: The security group that has already been set up.

  InstanceSubnet:
    Type: String
    Description: The subnet to be used.
    Default: subnet-55d8582f

  IpData:
    Type: String
    Description: ip data from the standalone node

  KeyData:
    Type: String
    Description: key data from the standalone node

  UserData:
    Type: String
    Description: User data aka cloud init data

  InstanceDiskSize:
    Type:  Number
    Description: The disk size of these instances.
    Default: 10

Resources:
  